import os
import uuid
from concurrent.futures import ThreadPoolExecutor

import pytest

psycopg = pytest.importorskip("psycopg")

from app.worker.job_store import IndexRunStore  # noqa: E402


@pytest.fixture()
def database_url() -> str:
    value = os.getenv("INGEST_TEST_DATABASE_URL")
    if not value:
        pytest.skip("INGEST_TEST_DATABASE_URL is not set")
    return value


@pytest.fixture()
def repo_schema(database_url: str):
    schema = f"repo_test_{uuid.uuid4().hex}"
    with psycopg.connect(database_url) as conn:
        conn.execute(f'CREATE SCHEMA "{schema}"')
        conn.execute(
            f'''
            CREATE TABLE "{schema}".repositories (
                "Id" uuid PRIMARY KEY,
                "NormalizedUrl" text NOT NULL,
                "SelectedBranch" text NULL,
                "DefaultBranch" text NULL
            )
            '''
        )
        conn.execute(
            f'''
            CREATE TABLE "{schema}".index_runs (
                "Id" uuid PRIMARY KEY,
                "RepositoryId" uuid NOT NULL,
                "Status" text NOT NULL,
                "Stage" text NOT NULL,
                "ProgressPct" integer NOT NULL,
                "ProgressCurrent" integer NOT NULL,
                "ProgressTotal" integer NOT NULL,
                "Attempt" integer NOT NULL,
                "MaxAttempts" integer NOT NULL,
                "WorkerId" text NULL,
                "LeaseUntil" timestamptz NULL,
                "HeartbeatAt" timestamptz NULL,
                "StartedAt" timestamptz NULL,
                "FinishedAt" timestamptz NULL,
                "ErrorCode" text NULL,
                "ErrorMessage" text NULL,
                "UpdatedAt" timestamptz NOT NULL,
                "CreatedAt" timestamptz NOT NULL
            )
            '''
        )
        conn.execute(
            f'''
            CREATE TABLE "{schema}".index_run_events (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "IndexRunId" uuid NOT NULL,
                "Level" text NOT NULL,
                "Stage" text NOT NULL,
                "Message" text NOT NULL,
                "PayloadJson" jsonb NULL,
                "CreatedAt" timestamptz NOT NULL
            )
            '''
        )

    try:
        yield schema
    finally:
        with psycopg.connect(database_url) as conn:
            conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')


def test_claim_next_allows_only_one_worker(database_url: str, repo_schema: str) -> None:
    repository_id, run_id = _insert_queued_run(database_url, repo_schema)
    store = IndexRunStore(database_url, repo_schema, lease_seconds=120)

    with ThreadPoolExecutor(max_workers=2) as executor:
        results = list(executor.map(store.claim_next, ["worker-a", "worker-b"]))

    claimed = [result for result in results if result is not None]
    assert len(claimed) == 1
    assert claimed[0].id == str(run_id)
    assert claimed[0].repository_id == str(repository_id)
    assert claimed[0].attempt == 1


def test_claim_next_reclaims_expired_running_run(database_url: str, repo_schema: str) -> None:
    _, run_id = _insert_queued_run(database_url, repo_schema)
    store = IndexRunStore(database_url, repo_schema, lease_seconds=120)

    first = store.claim_next("worker-a")
    assert first is not None

    with psycopg.connect(database_url) as conn:
        conn.execute(
            f'''
            UPDATE "{repo_schema}".index_runs
            SET "LeaseUntil" = now() - interval '1 second'
            WHERE "Id" = %s
            ''',
            (run_id,),
        )

    second = store.claim_next("worker-b")
    assert second is not None
    assert second.id == str(run_id)
    assert second.attempt == 2


def _insert_queued_run(database_url: str, schema: str) -> tuple[uuid.UUID, uuid.UUID]:
    repository_id = uuid.uuid4()
    run_id = uuid.uuid4()
    with psycopg.connect(database_url) as conn:
        conn.execute(
            f'''
            INSERT INTO "{schema}".repositories
                ("Id", "NormalizedUrl", "SelectedBranch", "DefaultBranch")
            VALUES (%s, %s, %s, %s)
            ''',
            (repository_id, "https://github.com/example/project", "main", None),
        )
        conn.execute(
            f'''
            INSERT INTO "{schema}".index_runs
                (
                    "Id",
                    "RepositoryId",
                    "Status",
                    "Stage",
                    "ProgressPct",
                    "ProgressCurrent",
                    "ProgressTotal",
                    "Attempt",
                    "MaxAttempts",
                    "CreatedAt",
                    "UpdatedAt"
                )
            VALUES (%s, %s, 'queued', 'queued', 0, 0, 0, 0, 3, now(), now())
            ''',
            (run_id, repository_id),
        )
    return repository_id, run_id
