import json
from pathlib import Path

import pytest
from git import Actor, Repo

from app.artifacts.file_inventory import build_file_inventory_artifact


def test_build_file_inventory_artifact_is_deterministic_and_classifies_files(tmp_path: Path) -> None:
    _write_text(tmp_path / "README.md", "# hello\n")
    _write_text(tmp_path / "cmd" / "main.go", "package main\nfunc main() {}\n")
    _write_text(tmp_path / "config" / "app.yaml", "port: 8080\n")
    _write_text(tmp_path / "pkg" / "service_test.go", "package pkg\n")
    _write_text(
        tmp_path / "internal" / "generated.pb.go",
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage internal\n",
    )
    _write_text(tmp_path / "vendor" / "github.com" / "pkg" / "lib.go", "package pkg\n")
    _write_binary(tmp_path / "bin" / "tool.bin", b"\x00\x01\x02\x03")

    repo = Repo.init(tmp_path)
    repo.index.add([str(path.relative_to(tmp_path)) for path in sorted(tmp_path.rglob("*")) if path.is_file()])
    actor = Actor("DopDoc", "dopdoc@example.com")
    repo.index.commit("init", author=actor, committer=actor)

    commit = repo.head.commit
    artifact = build_file_inventory_artifact(
        tmp_path,
        repository_id="repo-id",
        snapshot_id="snapshot-id",
        snapshot_metadata={
            "branch_name": "main",
            "commit_sha": commit.hexsha.lower(),
            "tree_hash": commit.tree.hexsha.lower(),
            "go_files_total": 4,
            "readme_files_total": 1,
            "bytes_total": sum(path.stat().st_size for path in tmp_path.rglob("*") if path.is_file()),
        },
    )

    document = json.loads(artifact.payload.decode("utf-8"))
    files = document["files"]

    assert artifact.artifact_kind == "file_inventory"
    assert artifact.schema_version == 1
    assert artifact.row_count == 7
    assert artifact.storage_key.endswith("/analysis/file_inventory.schema-v1.json")

    assert [item["path"] for item in files] == sorted(item["path"] for item in files)
    assert document["summary"]["kind_counts"] == {
        "binary": 1,
        "config": 1,
        "generated": 1,
        "go": 1,
        "markdown": 1,
        "test": 1,
        "vendor": 1,
    }

    by_path = {item["path"]: item for item in files}
    assert by_path["README.md"]["kind"] == "markdown"
    assert by_path["cmd/main.go"]["kind"] == "go"
    assert by_path["config/app.yaml"]["kind"] == "config"
    assert by_path["pkg/service_test.go"]["kind"] == "test"
    assert by_path["internal/generated.pb.go"]["kind"] == "generated"
    assert by_path["vendor/github.com/pkg/lib.go"]["kind"] == "vendor"
    assert by_path["bin/tool.bin"]["kind"] == "binary"
    assert by_path["bin/tool.bin"]["line_count"] == 0


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_binary(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
