import json
from pathlib import Path

from git import Actor, Repo

from app.artifacts.go_symbols import build_go_symbols_artifact


def test_build_go_symbols_artifact_is_deterministic_and_extracts_symbol_metadata(tmp_path: Path) -> None:
    _write_text(
        tmp_path / "internal" / "service.go",
        """package service

import (
    "context"
    fmtalias "fmt"
    . "strings"
    _ "net/http/pprof"
)

/*
Service manages users.
*/
type Service struct{}

type Mode string

// Repository loads users.
type Repository interface {
    Find(ctx context.Context, id string) (string, error)
}

// NewService builds Service.
func NewService[T any](ctx context.Context) *Service {
    fmtalias.Println(ToUpper("ready"))
    return &Service{}
}

func (s *Service) Handle(id string) error {
    return nil
}
""",
    )
    _write_text(
        tmp_path / "internal" / "generated.pb.go",
        """// Code generated by protoc-gen-go. DO NOT EDIT.
package service

type Generated struct{}
""",
    )
    _write_text(
        tmp_path / "pkg" / "service_test.go",
        """package service

import "testing"

func TestHandle(t *testing.T) {}
""",
    )
    _write_text(
        tmp_path / "vendor" / "example" / "lib.go",
        """package lib

func Vendor() {}
""",
    )

    repo = Repo.init(tmp_path)
    repo.index.add([str(path.relative_to(tmp_path)) for path in sorted(tmp_path.rglob("*")) if path.is_file()])
    actor = Actor("DopDoc", "dopdoc@example.com")
    repo.index.commit("init", author=actor, committer=actor)

    commit = repo.head.commit
    metadata = {
        "branch_name": "main",
        "commit_sha": commit.hexsha.lower(),
        "tree_hash": commit.tree.hexsha.lower(),
        "go_files_total": 4,
        "readme_files_total": 0,
        "bytes_total": sum(path.stat().st_size for path in tmp_path.rglob("*") if path.is_file()),
    }

    artifact_one = build_go_symbols_artifact(
        tmp_path,
        repository_id="repo-id",
        snapshot_id="snapshot-id",
        snapshot_metadata=metadata,
    )
    artifact_two = build_go_symbols_artifact(
        tmp_path,
        repository_id="repo-id",
        snapshot_id="snapshot-id",
        snapshot_metadata=metadata,
    )

    assert artifact_one.payload == artifact_two.payload
    assert artifact_one.checksum_sha256 == artifact_two.checksum_sha256
    assert artifact_one.artifact_kind == "go_symbols"
    assert artifact_one.schema_version == 1
    assert artifact_one.storage_key.endswith("/analysis/go_symbols.schema-v1.json")
    assert artifact_one.row_count == 8

    document = json.loads(artifact_one.payload.decode("utf-8"))

    assert document["summary"] == {
        "files_with_parse_errors_total": 0,
        "files_with_symbols_total": 4,
        "go_files_total": 4,
        "kind_counts": {
            "function": 3,
            "interface": 1,
            "method": 1,
            "struct": 2,
            "type": 1,
        },
        "packages_total": 2,
        "symbols_total": 8,
    }

    files_by_path = {item["path"]: item for item in document["files"]}
    service_file = files_by_path["internal/service.go"]
    assert service_file["package"] == "service"
    assert service_file["parse_error"] is False
    assert service_file["symbols_total"] == 5
    assert service_file["imports"] == [
        {"is_blank": False, "is_dot": False, "name": None, "path": "context"},
        {"is_blank": False, "is_dot": False, "name": "fmtalias", "path": "fmt"},
        {"is_blank": False, "is_dot": True, "name": ".", "path": "strings"},
        {"is_blank": True, "is_dot": False, "name": "_", "path": "net/http/pprof"},
    ]

    symbols_by_name = {(item["qualified_name"], item["file_path"]): item for item in document["symbols"]}

    new_service = symbols_by_name[("service.NewService", "internal/service.go")]
    assert new_service["kind"] == "function"
    assert new_service["signature"] == "func NewService[T any](ctx context.Context) *Service"
    assert new_service["doc_comment"] == "NewService builds Service."
    assert new_service["type_parameters"] == "[T any]"
    assert new_service["receiver"] is None

    handle = symbols_by_name[("service.Service.Handle", "internal/service.go")]
    assert handle["kind"] == "method"
    assert handle["signature"] == "func (s *Service) Handle(id string) error"
    assert handle["receiver"] == {
        "base_type": "Service",
        "is_pointer": True,
        "text": "(s *Service)",
        "type": "*Service",
    }

    repository = symbols_by_name[("service.Repository", "internal/service.go")]
    assert repository["kind"] == "interface"
    assert repository["signature"] == "type Repository interface"
    assert repository["doc_comment"] == "Repository loads users."

    mode = symbols_by_name[("service.Mode", "internal/service.go")]
    assert mode["kind"] == "type"
    assert mode["signature"] == "type Mode string"
    assert mode["is_alias"] is False

    generated = symbols_by_name[("service.Generated", "internal/generated.pb.go")]
    assert generated["kind"] == "struct"
    assert generated["is_generated"] is True

    test_symbol = symbols_by_name[("service.TestHandle", "pkg/service_test.go")]
    assert test_symbol["kind"] == "function"
    assert test_symbol["is_test"] is True

    vendor_symbol = symbols_by_name[("lib.Vendor", "vendor/example/lib.go")]
    assert vendor_symbol["kind"] == "function"
    assert vendor_symbol["is_vendor"] is True


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
