// <auto-generated />
using DopDoc.RepositoryService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DopDoc.RepositoryService.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20260525000100_AddDocumentationArtifactAttempt")]
    partial class AddDocumentationArtifactAttempt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            RepositoryModelConfiguration.Configure(modelBuilder, "repo");
#pragma warning restore 612, 618
        }
    }
}
