// <auto-generated />
using System;
using DopDoc.RepositoryService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DopDoc.RepositoryService.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    partial class RepositoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("repo")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.AnalysisArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProducedByIndexRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "ArtifactKind");

                    b.HasIndex("SnapshotId", "ArtifactKind", "SchemaVersion")
                        .IsUnique();

                    b.ToTable("analysis_artifacts", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentationRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("DocumentationRunId", "ArtifactKind");

                    b.ToTable("documentation_artifacts", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BaseSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressPct")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublishedManifestArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceIndexRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TemplateKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VerificationSummaryJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("RepositoryId", "SnapshotId", "CreatedAt");

                    b.HasIndex("Status", "LeaseUntil", "CreatedAt");

                    b.ToTable("documentation_runs", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentationRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SourceCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("TokenInput")
                        .HasColumnType("integer");

                    b.Property<int?>("TokenOutput")
                        .HasColumnType("integer");

                    b.Property<int>("UnsupportedClaims")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VerificationReportJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DocumentationRunId", "Ordinal");

                    b.HasIndex("DocumentationRunId", "SectionKey")
                        .IsUnique();

                    b.ToTable("documentation_sections", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationSectionSource", b =>
                {
                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("ChunkId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("StartLine")
                        .HasColumnType("integer");

                    b.Property<string>("SymbolName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("SectionId", "Ordinal");

                    b.ToTable("documentation_section_sources", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.IndexRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<int>("ChunksTotal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("FilesProcessed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressPct")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SymbolsTotal")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("VectorSize")
                        .HasColumnType("integer");

                    b.Property<int>("VectorsUpserted")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("RepositoryId", "CreatedAt");

                    b.HasIndex("Status", "LeaseUntil", "CreatedAt");

                    b.ToTable("index_runs", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.IndexRunEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IndexRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("IndexRunId", "Id");

                    b.ToTable("index_run_events", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActiveSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SelectedBranch")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("NormalizedUrl")
                        .IsUnique();

                    b.ToTable("repositories", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.RepositorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("BytesTotal")
                        .HasColumnType("bigint");

                    b.Property<string>("CommitAuthorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CommitAuthorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("CommitAuthoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CommitCommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommitMessage")
                        .HasColumnType("text");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CommitSubject")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FilesTotal")
                        .HasColumnType("integer");

                    b.Property<int>("GoFilesTotal")
                        .HasColumnType("integer");

                    b.Property<int>("ReadmeFilesTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "CommitSha")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "CreatedAt");

                    b.ToTable("repository_snapshots", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.UserRepository", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LastViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "RepositoryId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("user_repositories", "repo");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.AnalysisArtifact", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.RepositorySnapshot", "Snapshot")
                        .WithMany("AnalysisArtifacts")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationArtifact", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.DocumentationRun", "DocumentationRun")
                        .WithMany("Artifacts")
                        .HasForeignKey("DocumentationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DopDoc.RepositoryService.Domain.DocumentationSection", "Section")
                        .WithMany("Artifacts")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DocumentationRun");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationRun", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.Repository", "Repository")
                        .WithMany("DocumentationRuns")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DopDoc.RepositoryService.Domain.RepositorySnapshot", "Snapshot")
                        .WithMany("DocumentationRuns")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationSection", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.DocumentationRun", "DocumentationRun")
                        .WithMany("Sections")
                        .HasForeignKey("DocumentationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentationRun");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationSectionSource", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.DocumentationSection", "Section")
                        .WithMany("Sources")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.IndexRun", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.Repository", "Repository")
                        .WithMany("IndexRuns")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DopDoc.RepositoryService.Domain.RepositorySnapshot", "Snapshot")
                        .WithMany("IndexRuns")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repository");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.IndexRunEvent", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.IndexRun", "IndexRun")
                        .WithMany("Events")
                        .HasForeignKey("IndexRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexRun");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.RepositorySnapshot", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.Repository", "Repository")
                        .WithMany("Snapshots")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.UserRepository", b =>
                {
                    b.HasOne("DopDoc.RepositoryService.Domain.Repository", "Repository")
                        .WithMany("UserRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationRun", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.DocumentationSection", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.IndexRun", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.Repository", b =>
                {
                    b.Navigation("DocumentationRuns");

                    b.Navigation("IndexRuns");

                    b.Navigation("Snapshots");

                    b.Navigation("UserRepositories");
                });

            modelBuilder.Entity("DopDoc.RepositoryService.Domain.RepositorySnapshot", b =>
                {
                    b.Navigation("AnalysisArtifacts");

                    b.Navigation("DocumentationRuns");

                    b.Navigation("IndexRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
